data_ingestion:
  test_size: 0.3


feature_engineering:
  max_features: 50


model_building:
  active_model: random_forest
  random_state: 42

models:
  random_forest:
    n_estimators: 200
    max_depth: 15

  logistic_regression:
    max_iter: 1000




