data_ingestion:
  test_size: 0.2
feature_engineering:
  max_features: 5000
model_building:
  active_model: random_forest
  random_state: 42
models:
  random_forest:
    n_estimators: 200
    max_depth: 10
  logistic_regression:
    max_iter: 1000
    C: 1.0
